### ISSUE TITLE
SystemStackError (stack level too deep):

### ISSUE THREAD

**Issue by Trehana** [jsonapi-serializer/jsonapi-serializer#105]
## Expected Behavior
Caching of the serializer

## Actual Behavior
When i add

cache_options store: Rails.cache, namespace: 'jsonapi-serializer', expires_in: 1.hour
this error comes up 
SystemStackError (stack level too deep):

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - Version: 
  - Ruby version:2.6.2

**Comment by stas** [comment]
Hello @Trehana

I'm afraid we need some more details on how exactly this is used. Is it possible to at least get the initial parts of the backtrace maybe? Otherwise we can't really reproduce it, sorry.
