### ISSUE TITLE
Missing condition for custom attribute documentation

### ISSUE THREAD

**Issue by dcangulo** [jsonapi-serializer/jsonapi-serializer#107]
I have been banging my head in the last 2 days in trying to accomplish this and hopefully, we can add it in the documentation in case other people will encounter the same issue I had.

What I am trying to accomplish is a condition for the custom attributes.

In the documentation we have **custom attributes**:
```ruby
attribute :name_with_year do |object|
  "#{object.name} (#{object.year})"
end
```

And **conditional**:
```ruby
attribute :release_year, if: Proc.new { |record|
  # Release year will only be serialized if it's greater than 1990
  record.release_year > 1990
}
```

After trying several different syntaxes to accomplish using both cases what worked was the following code:
```ruby
attribute :custom_attribute, :if => Proc.new { true } do |object|
  'custom attribute'
end
```

I don't know if my approach is correct. If it does maybe we can add it in the documentation? I can create the PR if you're open to it.

**Comment by stas** [comment]
@dcangulo thank for the feedback.

I think it's fair to include the attribute block in the example, along with the conditional block if that's what you mean by the missing documentation.
