### ISSUE TITLE
Key transforms break 'fields' and 'include'

### ISSUE THREAD

**Issue by trlorenz** [jsonapi-serializer/jsonapi-serializer#119]
## Expected Behavior

The 'include' and 'fields' options should work as documented regardless of whether a key transform is in use, or whether a relationship has been "aliased."

## Actual Behavior

When a key transform is in use or a relationship has been "aliased," filtering attributes on the relationship via 'fields' doesn't work; all attributes for the relationship are returned.

## Steps to Reproduce the Problem

Though the problem with relationship aliasing is similar, let's look at the simpler key transform problem:

Assuming a model _Client_ that has_one _ClientBillingConfiguration_, and assuming a _ClientBillingConfiguration_ that has attributes _billing_self_service_price_in_cents_, _billing_trial_in_days_, and _billing_type_:

If in the ClientSerializer you have...

```ruby
set_key_transform :camel_lower

has_one :client_billing_configuration
```

...and then you say...

```ruby
ClientSerializer.new(a_client, include: [:client_billing_configuration], fields: {client_billing_configuration: [:billing_type]}).serializable_hash
```

...the serializer will return a hash where the included _client_billing_configuration_ record has all attributes, not just the requested _billing_type_ attribute.

I found this at the bottom of serialization_core.rb in #get_included_records:

```ruby
included_records << serializer.record_hash(inc_obj, fieldsets[record_type], includes_list, params)
```

In the case above, _fieldsets_ is {:client_billing_configuration=>[:billing_type]} as you'd probably expect, but _record_type_ is :clientBillingConfiguration. So clearly no fieldset makes it into #record_hash, and no filtering happens.

It seems likely that the line in serialization_core.rb should be...

```ruby
included_records << serializer.record_hash(inc_obj, fieldsets[relationship_item.name], includes_list, params)
``` 

...which would pick the correct fieldset. After making that change, though, and letting things go a little further, you wind up in #attributes_hash (via #record_hash)...

```ruby
attributes = attributes_to_serialize
attributes = attributes.slice(*fieldset) if fieldset.present?
```

...where you've now got the correct fieldset (in this case, [:billing_type]), but the keys of attributes_to_serialize are all camel-case...

```ruby
=> {:id=>#<FastJsonapi::Attribute:0x00007fc57c800298 @conditional_proc=nil, @key=:id, @method=#<Proc:0x00007fc57c4fded8(&:id)>>,
 :billingManagedServicePrice=>
  #<FastJsonapi::Attribute:0x0000561ae699b6a8
   @conditional_proc=nil,
   @key=:billingManagedServicePrice,
   @method=#<Proc:0x0000561ae699b798(&:billing_managed_service_price_in_cents)>>,
 :billingType =>
# etc...
```

...so attributes_to_serialize gets sliced to nothing.

## Specifications

  - Version: 2.1.0
  - Ruby version: 2.7.1

**Comment by stas** [comment]
@trlorenz sorry for not being able to take a look at this in the meantime... Did you figure it out or it was just a false alarm...?!

**Comment by trlorenz** [comment]
@stas Hey, no worries and thanks for the reply!

It was bad assumptions on my part, probably. But... since I've got you, let me ask:

If you've got a record type of :foo_bar, and you're using a key transform of :camel_lower, should you be asking for {fields: {foo_bar: ['field_one', 'field_two', ...]} or {fields: {fooBar: ['fieldOne', 'fieldTwo', ...}}? I was assuming the former, because I was assuming key transforms are meant to affect serializer output, only. But the latter works; the former doesn't. So the latter is the correct usage, yeah?

**Comment by stas** [comment]
> But the latter works; the former doesn't. So the latter is the correct usage, yeah?

Yep, the case type should be respected across the full implementation. I'm happy it all works for you!

**Comment by trlorenz** [comment]
Right on. And thanks for the work you've put into this.

**Comment by kitsuneyo** [comment]
Hi @trlorenz 

I've run into this issue too.

>If you've got a record type of :foo_bar, and you're using a key transform of :camel_lower, should you be asking for {fields: {foo_bar: [:field_one, :field_two, ...]} or {fields: {fooBar: [:fieldOne, :fieldTwo, ...}}? I was assuming the former, because I was assuming key transforms are meant to affect serializer output, only. But the latter works; the former doesn't.

The latter doesn't work for me - did you have to do anything special to get it working?

**Comment by trlorenz** [comment]
Ugh, sorry... I wish I could remember the details. It was just a little too long ago.

I do remember getting set_key_transform working as the docs described, after letting go of my bad assumptions. And I remember then realizing it wasn't going to work for me anyway.

I did finally get everything working how I wanted -- I wanted the front end to speak camel and the back end to speak snake, coming and going,  and I didn't want to have to think about it beyond that -- but I didn't use set_key_transform anywhere. It didn't work consistently for me for some edge cases, as I recall, and I was close to the edge in a number of places. (Something having to do with introspecting the associations created by JSONAPI::Serializer for use in processing incoming request params.)

I wound up writing my own case-transform system that worked for incoming as well as outgoing data, and worked well with all the additional stuff I wanted it to do at the time. But I can't remember how I got set_key_transform working after asking my question here, or why after that I gave up on it. That experimentation never made it to commit. (I'm not saying you should give up on it -- I'm sure it's fine for 99% of use cases. I guess it depends on how far outside the box you're operating.)

Sorry, wish I could be of more help.

**Comment by kitsuneyo** [comment]
@trlorenz It's helpful enough that you confirmed there's no complete solution using `set_key_transform`, so thank you! I've decided to use snake_case across my API, since it's easier to modify my front-ends to work with that than to get camelCase working here.

Just to clarify, `set_key_transform` did work out of the box with `fields` queries, just the way you described above. I had simply broken it by doing some `deep_transform_keys` stuff in the Application Controller that I'd forgotten about. But, I also had some other issues in jsonapi.rb that I couldn't get past, like missing `pointer` in errors when the field name has more than one word.

Great gem overall though.
