### ISSUE TITLE
Memoization for helper methods?

### ISSUE THREAD

**Issue by dmytro-savochkin** [jsonapi-serializer/jsonapi-serializer#124]
Hello.

Is there a recommended way to achieve memoization in helper methods?
Basically I have several attributes which call a computation heavy method from a model. I'd like to be able to memoize its result for a particular instance of a serializer. I can achieve it like this:

```
class TestSerializer
  include JSONAPI::Serializer

  attribute :attr1 do |object|
    compute(object)
  end

  attribute :attr2 do |object|
    compute(object)
  end

  def self.compute(object)
    @compute ||= object.do_something_heavy
  end
end
```

But Rubocop warns me this is an offense of ThreadSafety/InstanceVariableInClassMethod.
Another way I can think of would be to calculate the value of `compute` before and pass it to the serializer with `params`.

Are there better alternatives?

**Comment by stas** [comment]
@dmytro-savochkin would you consider doing the memoization on the object-side (model, or whatever you're throwing into the serializer)?

I generally advise keeping the serializers away from logic/computations...

**Comment by dmytro-savochkin** [comment]
> @dmytro-savochkin would you consider doing the memoization on the object-side (model, or whatever you're throwing into the serializer)?
> 
> I generally advise keeping the serializers away from logic/computations...

@stas Well, yes, probably I'll be doing what you suggested or passing it as params.
I was asking because we are currently in a middle of migration from active-model-serializers to jsonapi-serializer and memoized helpers were one of the things we could do before. 

Ideally though I think it would be nice to have such a thing here, it's not necessary something heavy, just something you'd rather not repeat.

**Comment by stas** [comment]
@dmytro-savochkin I don't think it's worth exploring that direction for one particular reason: performance.

The architecture of the `jsonapi-serializer` looks closer to a bunch of static methods than to an OOP architecture where a bunch of objects are initialized and passed around.

Another architectural issue/concept to explore here: **is memoization of the object attributes really a serializer concern?!**

I'll move ahead and close this, but I encourage everyone to share any thoughts/feedback.

@dmytro-savochkin thanks for starting the conversation...
