### ISSUE TITLE
Cannot serialize link to Active Storage attachment

### ISSUE THREAD

**Issue by ajeffika** [jsonapi-serializer/jsonapi-serializer#131]
Serializer doesn't allow to output url of attached image/attachment (while using Active Storage)

I wanted to serialize attachment from a model(using Active storage) but there seems to be no way to do that.
How do I get a link from an ActiveStorage attachment?

```
rails_blob_path
url_for
```
 are not recognized within the serializer, and including whichever of the url helpers doesn't resolve the problem. 

  - Version: 2.1.0
  - Ruby version: 2.6.3
  - Rails version: 6.0.2.2

**Comment by davideluque** [comment]
How did you solve this? I am having the same issue

**Comment by davideluque** [comment]
> How did you solve this? I am having the same issue

#157

**Comment by janmistarz** [comment]
Yeah, i did, i figured that i had a bug in my code

```
  attribute :logo do |object|
    Rails.application.routes.url_helpers.rails_blob_path(object.logo, only_path: true)
  end
  ```
  thats how i went about it. it works I believe there might be a more elegant solution, but i went with that

**Comment by davideluque** [comment]
Thanks! I found this solution somewhere:

```ruby
class FoodItemSerializer
  include JSONAPI::Serializer
  singleton_class.include Rails.application.routes.url_helpers

  attribute :image_url do |object|
    rails_blob_url(object.image, only_path: true) if object.image.attached?
  end
end
```
