### ISSUE TITLE
Deserialization options

### ISSUE THREAD

**Issue by JorgeGarciaxyz** [jsonapi-serializer/jsonapi-serializer#132]
Hello there, I've been using this gem and I love it.

I had a bad time while trying to find a good deserialization option but I found out a really good one
https://github.com/stas/jsonapi.rb

This gem also provides more functionality, not only deserialization.

I wanted to document this option somewhere visible so people can find it or even suggest other options.

Do you mind if I add this to the `README.md`? (to make things even more visible). I know the goal of this gem is to serialize stuff but if we can document deserialization options would be helpful.

Thank y'all!

**Comment by stas** [comment]
Thank you for the kind words @JorgeGarciaxyz :bow: :heart_eyes: 

I'll be more than happy to merge documentation/suggestions or community work related to `jsonapi/serializer`!

**Comment by JorgeGarciaxyz** [comment]
@stas sounds good! I'll work on this :raised_hands:

**Comment by JorgeGarciaxyz** [comment]
closed by #137
