### ISSUE TITLE
"Relationships" does not include expected data in chain of associated serializers

### ISSUE THREAD

**Issue by davidcparkk** [jsonapi-serializer/jsonapi-serializer#133]
## Expected Behavior
I am having difficulty loading data into my client-library data store due to missing data in the "relationships" node, however, I am making the correct controller method call such that I have the desired data in my "included" node. My understanding is that you need to have the data both in "relationships" and "included" to properly fetch, map, and store data in the data store.

I have 3 classes, `Student`, `CoursesStudent`, and `Course` with the following associations:
```
class Course < ActiveRecord::Base
  has_many :courses_students
  has_many :students, through: :courses_students
end

class CoursesStudent < ActiveRecord::Base
  belongs_to :student
  belongs_to :course
end

class Student < ActiveRecord::Base
  has_many :courses_students
  has_many :courses, through: :courses_students
end
```

The way my app is set up, I have the following serializers:
```
class CourseSerializer
  include JSONAPI::Serializer
  has_many :courses_students, serializer: CoursesStudentSerializer
end

class CoursesStudentSerializer
  include JSONAPI::Serializer
  belongs_to :student, serializer: StudentSerializer
  belongs_to :course, serializer: CourseSerializer
end

class StudentSerializer
  include JSONAPI::Serializer
  has_many :courses_students, serializer: CoursesStudentSerializer
end
```
With my controller method call of 

```render jsonapi: CourseSerializer.new(@course, include: [:courses_students, :'courses_students.student'])```

I was expecting my JSON to be:

```
{
  data: {
    id: "1",
    type: "course",
    relationships: {
      courses-students: {
        data: [{
            id: "2",
            type: "courses-student"
        }]
      },
      students: {
         data: [{
             id: "3",
             type: "student"
         }]
      }
    }
  },
  included: [
    {
      id: "2",
      type: "courses-student"
    },
    {
      id: "3",
      type: "student",
    }
  ]
}
```

## Actual Behavior

The actual JSON:
```
{
  data: {
    id: "1",
    type: "course",
    relationships: {
      courses-student: {
        data: [{
          id: "2",
          type: "courses-student"
        }]
      }
    }
  },
  included: [
    {
      id: "2",
      type: "courses-student"
    },
    {
      id: "3",
      type: "student",
    }
  ]
}
```

Is it not possible to have a chain of associated model serializers like I have listed above? I am not sure why the "relationships" does not have all the associated data, while the "included" node does. Any help is much appreciated, I am happy to provide further details

## Specifications

  - Version: 2.1.0
  - Ruby version: 2.6.5

**Comment by stas** [comment]
Hi there @davidcparkk 

I believe there's a missing relationship in your first serializer:
```diff
class CourseSerializer
  include JSONAPI::Serializer
  has_many :courses_students, serializer: CoursesStudentSerializer
+  has_many :students, serializer: StudentSerializer
end

```

The reason the `included` has the missing relationship data is because it's coming from the last include directive/serializer.

I hope this helps...

**Comment by davidcparkk** [comment]
@stas That did the trick :) Sorry to raise an issue over something so trivial, many thanks
