### ISSUE TITLE
How do I keep the association for new records that fail validation?

### ISSUE THREAD

**Issue by benlieb** [jsonapi-serializer/jsonapi-serializer#135]
When new model data has failing validations, I need those errors to come back to my front end and have the associations intact. The problem is that failing new records don't have an id, and they come back to the front end un-associated. 

I've been shimming this by providing a "fake" id on the rails side before serialization, and then that id is removed on the front end for re-submission. My solution isn't perfect and has limitations and issues. 

Is there a built-in way to do this or am I stuck with my own implementation. 

For what it's worth, this is my implementation so far, just to clarify what I'm doing. It's far from perfect and a lot of code for what seems like it should be a problem with a built-in solution. It's based on trying to iterate over the object tree being serialized and seeing if a "fake" id is needed. This still chokes on some things that can be passed via `include: []` 

```ruby
class BaseSerializer
  module ShimIdConcerns
    extend ActiveSupport::Concern
      
    private
  
    # Very Important! Controls relationship of json api assocs in front end
    # The id that is returned to the front end needs to be smarter than simply
    # the actual id or nil. The id is used to associate jsonapi objects to their
    # main resource whether they have an id yet or not. Sometimes these objects 
    # are not persisted, but have errors and need to be associated properly in the UI. 
    # Works in conjuncton with attribute :is_persisted
    def shim_id_on_failing_new_associations(resource, options)
      shim_id_on_failing_new_associations_recursive resource, options[:include].to_a
    end

    # dot_assocs: expects assocs in 'packages.package_services.service' format
    def shim_id_on_failing_new_associations_recursive(resource, dot_assocs)
      assocs = simplify_assocs(dot_assocs)

      assocs.each do |assoc_path|
        next if assoc_path.blank?
        segments = assoc_path.split('.') 
        method = segments.shift
        next unless resource.respond_to?(method)
        assoc = resource.send(method)

        if assoc.is_a?  ActiveRecord::Base
          shim_id(resource) 
          shim_id_on_failing_new_associations_recursive assoc, segments.join('.')
        elsif assoc.is_a?(ActiveRecord::Associations::CollectionProxy) || assoc.is_a?(Array)
          assoc.each do |one_of_many|
            shim_id_on_failing_new_associations_recursive one_of_many, segments.join('.')
          end
        end
      end
    end

    # Gives a temp id on failing or new resources so they can be associated in react
    # in jsonapi/react. Ensure this id is not re-submitted, however
    def shim_id(resource) 
      resource.id = rand(1000000000000) if resource.id.nil? && resource.new_record?
    end

    
    # turns
    #   [ :reservation, :'reservation.client', :'reservation.client.credit_card' ]
    # into
    #   [ "reservation.client.credit_card" ]
    # to avoid duplicate processing
    def simplify_assocs(dot_assocs)
      ap dot_assocs
      all = [dot_assocs].flatten.map(&:to_s)
      simp = []
      
      # yes quadratic, but will be little data
      all.each do |needle|
        matches = 0
        all.each do |hay|
          matches += 1 if hay.index(needle) === 0 
        end
        simp << needle if matches === 1
      end
      simp
    end
  end
end

```

**Comment by stas** [comment]
@benlieb I'm not sure I fully understand what you're trying to achieve here, but generally, I'm advising to stay away from nested resource creations requests. For example, instead of trying to dump a big payload into a request, consider splitting it into per-resource requests, where errors are handled inside an own context and can be treated properly on the UI.

Alternatively, just patch the serializers to generate an ID on the fly if you provide a parameter, ex: `YourSerializer.new(record, options: { validation_failed: true })` and so on... This will allow you to serialize records even though the ID is not present.

Apologies for the late reply btw. I'll close this issue, but if it helps, do feel free to continue the conversation @benlieb

**Comment by benlieb** [comment]
@stas I'm actually speaking about responses from our rails app to our front end. We're not making the requests using jsonapi, but rather Rails' nested attributes structure. However when any nested object is not yet saved/persisted, the serializers skip it because it has no id. I'm basically shimming in my own "fake" ids before serializing so this won't happen. Then I remove the fake ids on the front end. 

My question is about if there is a "right" way to do this that is supported by the library or is it simply not conceived of and not possible with the library.

**Comment by stas** [comment]
@benlieb consider overwriting this method in your serializer to allow empty IDs:
https://github.com/jsonapi-serializer/jsonapi-serializer/blob/master/lib/fast_jsonapi/serialization_core.rb#L121-L127

I think that should help...

**Comment by benlieb** [comment]
@stas that's pretty deep into the inner workings of the serializer, and I'd be concerned about unintended side-effects. Could you give me a hint about how you'd suggest I approach this? Would it be just to remove the exception raising and leave the rest the same? Or since it says that "id is a mandatory field in the jsonapi spec" is this where you suggest I assign the temporary id?

Thanks for your input.

**Comment by stas** [comment]
JSONAPI spec requires a non-blank value. That's what it takes to respect the spec, so removing the exception is canceling that part and only that...

**Comment by benlieb** [comment]
@stas in that case, a better approach might be to use this method to assign a temporary id. My code above is complex and probably brittle. If I could get away with something less verbose. 

It seems like `record_id` is a configurable method to call on the object to get its `id`. I'm pretty sure I tried to use this initially but if I remember correctly, there were issues getting it to fully work. I think it had to do with `id` actually existing in multiple places in the serialized output, and this method only caught some of them. 

I'd have to check my repo.

**Comment by stas** [comment]
> It's very common for us to have unpersisted records that we need to serialize. I'm a bit baffled why the JSONAPI spec doesn't have a built-in way of solving this issue. Am I missing something?

It's not common to serialize invalid data. A client sends data, if it's invalid, you get errors, not data :smiley:

**Comment by benlieb** [comment]
Well I suppose whether it's common is a subjective issue. But what is common for us is to show errors for failing associated objects. This form is a simple example I cannot associate errors with failing objects without shimming the id. The form submits to /people/x with nested email addresses, addresses, phone numbers etc. 

![image](https://user-images.githubusercontent.com/634562/99584503-e42fb900-2999-11eb-8f8f-765b9afed074.png)

**Comment by stas** [comment]
@benlieb I don't think discussing the JSONAPI spec is in the scope of this library. I advise you to start a conversation regarding your concerns within the JSONAPI community: https://github.com/json-api/json-api

Thank you for considering this library for your project! :bow:
