### ISSUE TITLE
Cache not honoring params

### ISSUE THREAD

**Issue by bradherman** [jsonapi-serializer/jsonapi-serializer#138]
## Expected Behavior

Consider the following example:
```
class ObjectSerializer
  include JSONAPI::Serializer

  cache_options store: Rails.cache, namespace: 'jsonapi-serializer', expires_in: 1.hour
  ...

  attribute :extra_data, if: Proc.new { |record, params| !params[:summary] } do |object|
    ...
  end
end

a = ObjectSerializer.new(object, { params: { summary: true } }).as_json
b = ObjectSerializer.new(object, { params: { summary: false } }).as_json

# a != b
# a['data']['attributes'].key?('extra_data') => false
# b['data']['attributes'].key?('extra_data') => true
```
The cache should respect the params.

## Actual Behavior

The cacheing mechanism is not honoring the params.

## Steps to Reproduce the Problem

  1.  Set up conditional attrs using passed in params and block evaluation as seen above
  2. Ensure cacheing is turned on
  3. Call serializer w/ summary: true and summary:  false

## Specifications

  - Version: 2.1.0
  - Ruby version: 2.7.1

**Comment by bradherman** [comment]
Dug into the code a bit and looks like it's just not designed to create a new cache based on params values... I suggest adding the same sort of code as we have in the SerializationCore in the `record_cache_options` method, along the lines of:

```ruby
        if !params.empty?
          params_key = params.empty? ? nil : params.to_a.sort_by {|k,v| k.to_s}.join(':')

          if params_key&.length.to_i > 40
            params_key = Digest::SHA1.hexdigest(params_key)
          end

          options[:namespace] += "-params:#{params_key}" if params_key
        end
```

**Comment by stas** [comment]
@bradherman I actually had to deal with this when I refactored the cache API in:
https://github.com/jsonapi-serializer/jsonapi-serializer/commit/4d1a764abcec21fa3aaa101474da9dc7eb0d9659

To be honest, I'm not sure we want to enable something like that on a general basis. I'd rather leave folks to use the existing cache API and handle it specifically. The way we approached, this was by setting up a cache-specific serializer we could extend from. Consider the example below:

```ruby
require 'active_support/cache'

class CachedSerializer < BaseSerializer
  cache_options(
    store: ActiveSupport::Cache::MemoryStore.new(size: 50.megabytes),
    namespace: 'jsonapi'
  ) if Rails.env.production?

  def self.record_cache_options(options, fieldset, include_list, params)
    opts = options.dup

    opts[:namespace] += ':with-summary' if params[:summary].present?

    super(opts, fieldset, include_list, params)
  end
end
```

Let me know what you think?

**Comment by bradherman** [comment]
Yeah makes sense... Definitely could get abused and/or be very ineffective with lots of params

**Comment by stas** [comment]
@bradherman please let me know if this can be closed for now. Thank you!

**Comment by bradherman** [comment]
@stas sorry for the delay... closing
