### ISSUE TITLE
Attributes not included in relationship

### ISSUE THREAD

**Issue by GMolini** [jsonapi-serializer/jsonapi-serializer#147]
Im not sure if its just the intended behaviour, since I just started using it and I have not seen any examples with what i would like to achieve, but im defining a relationship in my serializer (has_many, and belongs_to, it doesnt matter as they both behave the same), and the data of the relationship wont be serialized.

So lets say I have the following serializers:

```
FirstSerializer


 attributes :name, :email

 has_many :things, serializer: SecondSerializer

end


SecondSerializer

  attributes :name, :acronym

end
```

What is happening:
```
{
    "data": [
        {
            "id": "3",
            "type": "first",
            "attributes": {
                "name": "myname",
                "email": "myemail"
            },
            "relationships": {
                "things": {
                    "data": [
                        {
                            "id": "3",
                            "type": "second"
                        }
                    ]
                },
            }
        },
        --
```
What I would like to happen
```
{
    "data": [
        {
            "id": "3",
            "type": "first",
            "attributes": {
                "name": "myname",
                "email": "myemail"
            },
            "relationships": {
                "things": {
                    "data": [
                        {
                            "attributes": {
                              name: 'myothername',
                              acronym: 'myacronym'
                            }
                            "type": "second"
                        }
                    ]
                },
            }
        },
        --
```
Is it possible to load all the relationships data too?
Im using jsonapi-serializer 2.1.0

**Comment by stas** [comment]
@GMolini please review the JSONAPI spec, that's not how relationships work:
https://jsonapi.org/format/#document-resource-object-relationships

What you probably need is:
https://jsonapi.org/format/#document-compound-documents

I'll be closing this, since it's not related to the implementation.
