### ISSUE TITLE
Proc shortcuts do not work with Ruby 3.0

### ISSUE THREAD

**Issue by rmlockerd** [jsonapi-serializer/jsonapi-serializer#158]
## Expected Behavior
When 'aliasing' an attribute to a different name, you can pass the original as a proc shortcut, like so:

```ruby
class MovieSerializer
  include JSONAPI::Serializer

  attribute :released_in_year, &:year
end
```

## Actual Behavior
Using Ruby 3.0.0, however, this results in the following error:
```
ArgumentError:
wrong number of arguments (given 1, expected 0)
 # ./lib/fast_jsonapi/helpers.rb:10:in `call_proc'
 # ./lib/fast_jsonapi/scalar.rb:14:in `serialize'
 # ./lib/fast_jsonapi/serialization_core.rb:49:in `block in attributes_hash'
```
This appears to be caused by a change (or bug) in the way the parameters for Proc created by `Symbol.to_proc` are defined. 
In Ruby 3.0, the length of the parameters array returned for a Proc created using the `&:foo` shortcut is now 2, though in reality the Proc only requires to be passed the receiver object (i.e., it doesn't really take any parameters). Looks like the helper code needs to be a bit smarter about how it counts Proc parameters since it can't rely on just the length of that Array. I'll fiddle with it and submit a pull request.

## Steps to Reproduce the Problem
The existing test fixtures don't currently include an example of the proc shortcut, but by simply adding:
```
attribute :released_in_year, &:year
```
to the `MovieSerializer` fixture and running rspec using Ruby 3.0.0 will demonstrate the problem.

## Specifications

  - Version: 2.1.0
  - Ruby version: 3.0.0

**Comment by davidwparker** [comment]
Nice @rmlockerd - just had this one.

For others' Googling and getting here, the obvious temporary solution is to convert to a non-proc:

```ruby
attribute :released_in_year do |obj|
  obj.year
end
```

**Comment by ziggythehamster** [comment]
Just adding a reference, this would be fixed by #160 from what I can tell.

**Comment by johannesluedke** [comment]
It would be nice to see this merged on v2.x -- would make lives easier for everyone upgrading to Ruby 3 in the next time

**Comment by stas** [comment]
I'll prepare a release. Thank you everyone!

**Comment by kapso** [comment]
@stas Any timeline for releasing this?

Thanks.

**Comment by stas** [comment]
Apologies for a bit of delay with this one :see_no_evil: :bow: 

Also thank you for pushing me :heart:
