### ISSUE TITLE
Meta attribute for the collection size?

### ISSUE THREAD

**Issue by aximuseng** [jsonapi-serializer/jsonapi-serializer#159]
In this example:

```
class MovieSerializer
  include JSONAPI::Serializer

  set_type :movie  # optional
  set_id :owner_id # optional
  attributes :name, :year
  has_many :actors
  belongs_to :owner, record_type: :user
  belongs_to :movie_type
end
```

How would you add a meta attribute for the number os movies returned from the controller?

**Comment by stas** [comment]
Hey @aximuseng,
please take a look at this section in the documentation:
https://github.com/jsonapi-serializer/jsonapi-serializer#compound-document

**Comment by aximuseng** [comment]
Perfect - I missed that on the my first few passes of the docs - clearly was not obvious to me.  Thanks.
