### ISSUE TITLE
Set a custom ID in relationships

### ISSUE THREAD

**Issue by aximuseng** [jsonapi-serializer/jsonapi-serializer#161]
## Expected Behavior

I have a custom ID scheme for my data (trying to hide the 1,2,3... etc)

From the docs:

```
class MovieSerializer
  include JSONAPI::Serializer

  set_type :movie  # optional
  set_id :my_id_method
  attributes :name, :year
  has_many :actors
  belongs_to :owner, record_type: :user
  belongs_to :movie_type
end

class ActorMovieSerializer
  include JSONAPI::Serializer

  set_id :my_id_method
  attributes :name
  has_many :awards
end

```
and the output that I am looking for:

```
{
  "data": {
    "id": "QWE456",
    "type": "movie",
    "attributes": {
      "name": "test movie",
      "year": null
    },
    "relationships": {
      "actors": {
        "data": [
          {
            "id": "ABC123",
            "type": "actor"
          },
          {
            "id": "XYZ789",
            "type": "actor"
          }
        ]
      },
      "owner": {
        "data": {
          "id": "3",
          "type": "user"
        }
      }
    }
  }
}
```

## Actual Behavior

Except I get:

```
{
  "data": {
    "id": "QWE456",
    "type": "movie",
    "attributes": {
      "name": "test movie",
      "year": null
    },
    "relationships": {
      "actors": {
        "data": [
          {
            "id": "4",
            "type": "actor"
          },
          {
            "id": "5",
            "type": "actor"
          }
        ]
      },
      "owner": {
        "data": {
          "id": "3",
          "type": "user"
        }
      }
    }
  }
}
```

where the relationship ID always revert to the DB id value.  If I call the `ActorSerializer` it works fine.

Can I even do this?

**Comment by stas** [comment]
@aximuseng please take a look at the customizable options:
https://github.com/jsonapi-serializer/jsonapi-serializer#customizable-options

Specifically, you could provide a callable to the `id_method_name` on relationships to customize the ID's from relationships!

**Comment by aximuseng** [comment]
I actually tried that and based on the results I figured this was not what it was intended for.  I tried something like this:

```
class MovieSerializer
  include JSONAPI::Serializer

  set_type :movie  # optional
  set_id :my_id_method
  attributes :name, :year
  has_many :actors, id_method_name: :my_id_method
 end
```

and results in this:

```
{
  "data": {
    "id": "QWE456",
    "type": "movie",
    "attributes": {
      "name": "test movie",
      "year": null
    },
    "relationships": {
      "actors": {
        "data": [
          {
            "id": "QWE456",
            "type": "actor"
          },
          {
            "id": "QWE456",
            "type": "actor"
          }
        ]
      },
      "owner": {
        "data": {
          "id": "3",
          "type": "user"
        }
      }
    }
  }
}
```

The custom id for the parent is set for the child records.

**Comment by aximuseng** [comment]
It seems to work - in my case I accidentally called the id method on a model that the method doesn't exist.  When you do that it seems that it is then called on the parent.

**Comment by stas** [comment]
Cool, I'm glad it worked. I'll be closing this for now. :raised_hands:

**Comment by aximuseng** [comment]
Hmmm... not sure what's going on here.  Back to the old behavior.  Can this get opened again?

Again is the idea here that `Actor.last.my_id_method` results in in `ABC123` etc. OR is it `Movie.my_id_method` returns an array of the ID's to use in the relationship result?

**Comment by aximuseng** [comment]
@stas can you re-visit this?

There seems to be a disconnect:

```
has_many :actors,
  id_method_name: :my_id_method

belongs_to :studio,
  id_method_name: :my_id_method

{
  "data": {
    "id": "QWE456",
    "type": "movie",
    "attributes": {
      "name": "test movie",
      "year": null
    },
    "relationships": {
      "studio": {
        "data": [
          {
            "id": "ABC123",
            "name": "Studio ABC"
          }
        ]
      },
      "actors": {
        "data": [
          {
            "id": "QWE456",
            "type": "actor"
          },
          {
            "id": "QWE456",
            "type": "actor"
          }
        ]
      }
     }
    }
  }
}
```
When you have a `has_many` etc. the method needs to be called on the individual record NOT the parent object.

**Comment by stas** [comment]
@aximuseng I'm not sure where's the confusing part, the example you shared seems to work just fine. The documentation states as expected:
> Set custom method name to get ID of an object (If block is provided for the relationship, id_method_name is invoked on the return value of the block instead of the resource object)

https://github.com/jsonapi-serializer/jsonapi-serializer#customizable-options

**Comment by Luiyit** [comment]
Just in case, the id_method_name is a parent model method. Here is a functional example using uid like special id

```
class Movie < ApplicationRecord
    belongs_to :owner
    def get_owner_id
        self.owner.uid
    end
end

class MovieSerializer
   include JSONAPI::Serializer
   attributes :name

   set_id :uid
   belongs_to :owner, id_method_name: :get_owner_id
end

class OwnerSerializer
   include JSONAPI::Serializer
   attributes :name

   set_id :uid
end
```
if you save the uid in the parent record (database), you can set the column name in id_method_name, instead to declare a custom method per each relationship in the model.
