### ISSUE TITLE
SubclassNotFound when using an STI model as the owner.

### ISSUE THREAD

**Issue by TruRooms** [jsonapi-serializer/jsonapi-serializer#163]
## Expected Behavior
When using a serializer to to serialize a polymorphic relationship, the application is able to output an attribute for the related record.

Example:

With the below class structure:

```
class User > ApplicationRecord
  has_many :activities
end

class User::Admin > User
end

class Activity > ApplicationRecord
  belongs_to :owner, polymorphic: true
end

class ActivitySerializer
  include JSONAPI::Serializer
  belongs_to :owner, serializer: :user

  attribute :owner_name do |record|
    object.owner.name
  end
end
```

```
user = User.create(type: 'User::Admin', name: 'Bob')
activity = Activity.create(owner_id: user.id, owner_type: 'User')

ActivitySerializer.new(activity)
=> {
  id: 1, 
  attributes: { 
    owner_name: 'Bob' 
  }
}

## Actual Behavior

Output of the above example is:

```
"#<ActiveRecord::SubclassNotFound: Invalid single-table inheritance type: User::Admin is not a subclass of User>"
``

### 1
**IF** the field `owner_type` is set to be `User::Admin` the serializer does work. From what I can grok of the polymorphic relationships with single table inheritance, this is not the Rails way.
### 2
Using `User.find(owner_id).name` allows the correct class to be found and rendered in the serializer.

## Steps to Reproduce the Problem

  1. Fresh rails app, with models similar to the above.
  2. Create records and have the serialized output rendered.

## Specifications

  - Version: 2.1.0
  - Ruby version: 2.6.6

**Comment by TruRooms** [comment]
Added example app that reproduces the issue.

[https://github.com/TruRooms/serializer_test](https://github.com/TruRooms/serializer_test)

I wrote a basic spec to try and illustrate, but specs pass. Live testing still triggers the error.

**Comment by stas** [comment]
@TruRooms there are a couple of typos in your example, which I'll skip, but this exact part is what's causing you the issue:

```ruby
user = User.create(type: 'User::Admin', name: 'Bob')
activity = Activity.create(owner_id: user.id, owner_type: 'User')
```

Basically, you're creating an `User::Admin`, but you're trying to assign it to the activity as an `User`.

Instead I'd advise you to use the Rails API to get the job done, consider the same example:
```ruby
user = User::Admin.create(name: 'Bob')
activity = Activity.create(owner: user)
```

This way Rails will take care of the `owner_type` and `type`.

I'll be closing this for now since I don't see how is this related to this gem/library.
