### ISSUE TITLE
How do I disable cache?

### ISSUE THREAD

**Issue by pedrofurtado** [jsonapi-serializer/jsonapi-serializer#166]
How do I disable cache?

Using `cache_options enabled: false` emits a deprecation warning. So, what is the way to disable entirely the cache? 🤝 

Thanks!

**Comment by stas** [comment]
@pedrofurtado do not define the `cache_options` inside your serializer.

The way we have it, is two base classes (eg. `BaseSerializer` and `CachedSerializer < BaseSerializer`, where the last has the `cache_options` defined.

The rest of the serializers inherit from either the first one or the later.

Let me know if this helped. :bow:

**Comment by pedrofurtado** [comment]
@stas Thanks for feedback!

So, we have two options, right?

1. Not define `cache_options` inside my serializer class.
2. Define `cache_options store: nil`

The option 2 is valid? I saw in code that passing nil, they also ignore cache 👍

**Comment by stas** [comment]
@pedrofurtado if it works, then why not

**Comment by pedrofurtado** [comment]
Thanks a lot @stas ! 🤝
