### ISSUE TITLE
NameError (uninitialized constant <Model>Serializer)

### ISSUE THREAD

**Issue by SafeAF** [jsonapi-serializer/jsonapi-serializer#168]
## Steps to Reproduce the Problem

  1.gem 'jsonapi-serializer'
  2. bundle install
  3. rails g serializer Account site_url username site_name account_home_url slug
  4. rails console
  a = Account.first
   (0.8ms)  SELECT sqlite_version(*)
  Account Load (0.1ms)  SELECT "accounts".* FROM "accounts" ORDER BY "accounts"."id" ASC LIMIT ?  [["LIMIT", 1]]
 => #<Account id: 1, user_id: 1, site_url: "facebook.com", username: nil, ... 
3.0.0 :003 > AccountSerializer.new(a)
Traceback (most recent call last):
        1: from (irb):3:in `<main>'
NameError (uninitialized constant AccountSerializer)

serializers/account_serializer.rb:
class AccountSerializer
  include JSONAPI::Serializer
  attributes :site_url, :username, :site_name, :account_home_url, :slug

  has_many :posts
end

## Specifications

  - Version: latest
  - Ruby version: ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-linux]
  - Rails: 6.1.1

**Comment by stas** [comment]
@SafeAF could you please confirm you're running the #141 ?

If so, please confirm you have configured rails to pick up the serializers from `app/serializers`.

---

> We'd have to add the serializers path to the list of autoload paths in the Rails app config/application.rb:
> 
>```
>config.autoload_paths << 'app/serializers'
>```

**Comment by SafeAF** [comment]
config.autoload_paths << 'app/serializers'

worked for me. thank you. i didn't see it in the docs. and ive not used serializers in rails before.

**Comment by stas** [comment]
All good, glad it worked out. Please leave any feedback, I'll be happy to look into it! :bow:
