### ISSUE TITLE
Allow caching to be conditional based on params

### ISSUE THREAD

**Issue by kapso** [jsonapi-serializer/jsonapi-serializer#169]
I only want the object to be cached based on a variable in `params`. I imagine this is a common requirement.

So the use case is sometimes we return a "lite" version of the object vs. a "full" version of the object, and the object should only cached when returning a "full" version.

**Comment by stas** [comment]
Hey @kapso 

Would you be kind to review this comment if it works for you?
https://github.com/jsonapi-serializer/jsonapi-serializer/issues/148#issuecomment-729121595

**Comment by kapso** [comment]
@stas thanks will give it a look

**Comment by kapso** [comment]
@stas Judging from the comments on the method -  `Cache options helper. Use it to adapt cache keys/rules.`

...it looks like the method can be used to change the cache options, but it cannot be used to make caching conditional.

**Comment by stas** [comment]
@kapso I'll be closing this, but do feel free to continue the conversation if you find it helpful :bow:
