### ISSUE TITLE
Migrating from Netflix/fast_jsonapi

### ISSUE THREAD

**Issue by kapso** [jsonapi-serializer/jsonapi-serializer#170]
I followed these steps for migration (https://github.com/jsonapi-serializer/jsonapi-serializer#migrating-from-netflixfast_jsonapi) and the app works fine, deployed it on our staging, and all good.

But the interesting thing is, that our tests (RSpec) are failing with this error - `TypeError: no implicit conversion of nil into Hash`

```ruby
def show
  includes = [:product_images, :categories]
 
  render json: App::ProductSerializer.new(
    @product,
    include: includes,
    params: { product_full: true }
  ).serializable_hash.to_json
end
```

If I remove `include: includes,`, then the error goes away. Did I miss a step during migration?

Versions:
```
ruby '2.7.2'
gem 'rails', '6.1.2'
gem 'jsonapi-serializer', '2.1.0'
```

**Comment by stas** [comment]
@kapso do you have a backtrace you can share please :pray:

**Comment by kapso** [comment]
@stas That's the strange part, there's no backtrace.

**Comment by kapso** [comment]
@stas found the issue. Following up on this issue - https://github.com/jsonapi-serializer/jsonapi-serializer/issues/169

```ruby
def self.record_cache_options(options, fieldset, include_list, params)
  params[:product_full] ? super : {} # This works

  # The following was resulting in the above error with no stacktrace
  # super if params[:product_full] 
end
```

I am guessing I need to return an empty hash to stop the caching?

**Comment by stas** [comment]
> I am guessing I need to return an empty hash to stop the caching?

@kapso I'm not sure I follow. Are you asking about caching or about the exception here?

As for `record_cache_options` please follow the docs, it's all documented:
https://github.com/jsonapi-serializer/jsonapi-serializer/blob/master/lib/fast_jsonapi/serialization_core.rb#L90-L102

**Comment by kapso** [comment]
@stas the exception is resolved, so I am good. I will address the other issue here - #169 

Thanks.
