### ISSUE TITLE
Support for sparse-fieldsets when using a polymorphic relationship

### ISSUE THREAD

**Issue by kapso** [jsonapi-serializer/jsonapi-serializer#171]
So given the following serializer, where `worker` can be of type `EmployeeSerializer` or `ContractorSerializer`, how does sparse fieldset work when selecting different fields for `Employee` and `Contractor`?

```ruby
class CompanySerializer
  include JSONAPI::Serializer

  attributes :id, :name

  has_many :workers, polymorphic: true
end
```

**Comment by stas** [comment]
@kapso if a field is not available/restricted, JSONAPI spec suggests it will silently be ignored from the request. 

TL;DR, you can require any field, but only available ones will be included in the response. Please let us know if that's not the case and there's some error. :see_no_evil:

**Comment by kapso** [comment]
@stas 

Actually, this works - `fields: { employee: [:id, :name], contractor: [:id, :name, :contract_duration] }`

I was thinking, this will work - `fields: { worker: [:id, :name, :contract_duration] }`

**Comment by stas** [comment]
Glad you figured it out @kapso :bow:
