### ISSUE TITLE
Bump version 

### ISSUE THREAD

**Issue by williantenfen** [jsonapi-serializer/jsonapi-serializer#173]
I know version 3 is under development, but there's an important PR merged after the last bump for version 2. 
Shouldn't a new version or patch be available after PR: https://github.com/jsonapi-serializer/jsonapi-serializer/pull/125 ?

For now I'll use from master branch.. thanks...

**Comment by stas** [comment]
Closed in 3723505

Apologies for the delay :see_no_evil: :bow:
