### ISSUE TITLE
How can I include associations in an attribute collection?

### ISSUE THREAD

**Issue by benlieb** [jsonapi-serializer/jsonapi-serializer#176]
In my Reservation serializer I have a collection of computed reservations in an array, `some_other_reservations`. To be clear this is NOT an association, but a computed array of `Reservation` objects.

I also have a transfer association that is also a reservation.

```ruby
class ReservationSerializer < BaseSerializer
  include JSONAPI::Serializer
  
  has_one    :transfer, serializer: ReservationSerializer
  
  attribute  :some_other_reservations #an array of reservations
end
```

When I serialize this, the reservations in `some_other_reservations` don't have the `transfer` included. As far as I know, there is no way to do this. I tried to force this into an association, but it won't work, because the collection can't be computed via SQL.

I tried the method below, but it resulted in an infinite loop:

```ruby
  attribute  :some_other_reservations do |reservation|
    ReservationSerializer.new(reservation.some_other_reservations , include: [:transfer])
  end
```

**Comment by stas** [comment]
@benlieb I'm afraid that's not how JSON:API spec works.

Please consider taking a look at the compound documents spec:
https://jsonapi.org/format/#document-compound-documents

Basically, you can arbitrary include any relationship by nesting it, eg: `/?include=reservations.transfer.transfer_reservations` ...
https://jsonapi.org/format/#document-compound-documents

I'll be closing this, since I don't see how one is related to the other, but do feel free to continue the conversation :bow:

**Comment by benlieb** [comment]
For posterity, this is what I ended up using:

```ruby
  # Returns an array of all the serializers attributes except the ones passed in
  #
  # Jsonapi let's you specify what fields to include in a 'sparse set', 
  #   MovieSerializer.new(movie, { fields: { movie: [:name] } })
  #
  # But it doesn't let you exclude fields, so we can use exclude_fields 
  #   MovieSerializer.new(movie, { fields: { movie: MovieSerializer.exclude_fields([:name]) } })
  def self.exclude_fields(exclude=[])
    all_attributes     = attributes_to_serialize.keys  # stored as type in set_key_transform, so lower camelcase for now
    exclude_attributes = exclude.map{ |field| field.to_s.camelize(:lower).to_sym } # convert to lower camelcase

    all_attributes - exclude_attributes
  end
```
