### ISSUE TITLE
Custom Foreign_Key

### ISSUE THREAD

**Issue by AskBid** [jsonapi-serializer/jsonapi-serializer#179]
I have a database that I cannot modify as it is a read-only populated from a node I don't control.

This causes the tables to have `foreign_keys` that are different from the Rails default way.
You can see the current situation in the models below:

```ruby
# app/models/epoch_stake.rb
class EpochStake < DbSyncRecord
	self.table_name = 'epoch_stake'
	belongs_to :stake_address, foreign_key: :addr_id
end

# app/models/stake_address.rb
class StakeAddress < DbSyncRecord
    self.table_name = "stake_address"
	has_many :epoch_stakes, foreign_key: :addr_id
end
```
> `addr_id` rather than `stake_address_id`

I use a serializer in the relative controller:

```ruby
class EpochStakeController < ApplicationController
	def index
		epoch_stakes = EpochStake.all
		render json: EpochStakeSerializer.new(epoch_stakes)
	end
end
```

It seems though that when I try to tell the `JSONAPI::Serializer` to be aware of the different `foreign_key`, it doesn't take it into consideration:

```ruby
# app/serializers/epoch_stake_serializers.rb
class EpochStakeSerializer
  include JSONAPI::Serializer
  attributes :epoch_no, :amount
  belongs_to :stake_address, foreign_key: :addr_id
end
```

Infact when I query the controller (`/epoch_stakes`) with the configuration above I receive the following error, as if the serializer is trying to look for the association with the Rails default `foreign_key` rather than the one I specified in the serializer: 

```bash
NoMethodError: undefined method `stake_address_id' for #<EpochStake:0x00007fcf9f22ad50>
Did you mean?  stake_address
               stake_address=
from /Users/sergio/.rvm/gems/ruby-2.6.1/gems/activemodel-6.1.3/lib/active_model/attribute_methods.rb:469:in `method_missing'
```

Is there a way to tell the Serializer of the actual foreign_key?

## Specifications

  - Version: 2.2.0
  - Ruby version: 2.6.1p33

**Comment by stas** [comment]
Thanks @AskBid 

Could you play a bit with the available options you can find here:
https://github.com/jsonapi-serializer/jsonapi-serializer#customizable-options

Particularly the `id_method_name` and `object_method_name` could work.
:pray:

**Comment by AskBid** [comment]
Thanks, I've tried with `id_method_name` it looked ok, but then noticed that the relationship object was returning an empty object (no attributes) even though something is supposed to be there.
```json
"{"data": [{
    "id": "6763981",
    "type": "epoch_stake",
    "attributes": {
      "epoch_no": 257,
      "amount": "0.0"
    },
    "relationships": {
      "stake_address": {
        "data": {
          "id": "1",
          "type": "stake_address"
         }  //<= no attributes?
      }
    }]
}"
```
So I thought it was meant for something else.

**Comment by AskBid** [comment]
`id_method_name` worked out well, I was just forgetting to include the associated model:
```
render json: EpochStakeSerializer.new(epoch_stakes, include: [:stake_address]) #id_method_name was working but forgot this include.
```

**Comment by AskBid** [comment]
`id_method_name` is the solution, attributes were not appearing because I wasn't calling `include:` when instantiating the Serializer.
