### ISSUE TITLE
How to rename a key

### ISSUE THREAD

**Issue by exocode** [jsonapi-serializer/jsonapi-serializer#182]
## Expected Behavior

```ruby
class MyModel

  def a
     [1,2,3]
  end
end

class MySerializer
  include JSONAPI::Serializer
  attribute :old, key: :new
end

```
MySerializer.new(my_model)
`# -> "new" => [1,2,3]`
## Actual Behavior
`# -> "old" => [1,2,3]`

**Comment by stas** [comment]
Hi there @exocode 

Please take a look at the `attribute` API call. Basically, you can pass a block to it to call your _new_ method preserving the old key:
https://github.com/jsonapi-serializer/jsonapi-serializer/blob/master/spec/fixtures/movie.rb#L53-L55
