### ISSUE TITLE
[Help] Passing params through serializers

### ISSUE THREAD

**Issue by gastoncusimano** [jsonapi-serializer/jsonapi-serializer#186]
Hi! I'm migrating from ams and I have a controller where I serialize a collection and inside its serializer I wanted to one by one serialize another object(relation). I'm trying to pass params like it is described on the readme but I cannot make it work.

### My Controller
```ruby
ApplicantIndexSerializer.new(paged_collection).serializable_hash
```

### Serializer1
```ruby
 class ApplicantIndexSerializer
  include JSONAPI::Serializer
  ...
  attributes :selection_processes do |object|
    SelectionProcessesIndexSerializer.new(object.selection_processes.uniq, {params: { applicant: object }})
  end
  has_many :selection_processes, serializer: SelectionProcessesIndexSerializer
end
```

### Serializer2
```ruby
class SelectionProcessesIndexSerializer
  include JSONAPI::Serializer
  ...
  attributes :applicant_stage do |object, params|
    ... 
  end
end
```

And if I wanted to filter by the object (applicant) that I sent through params its returns `{}`

**Comment by stas** [comment]
Hey @gastoncusimano 

I'm afraid this doesn't work like that. The serializers pass over the `params` to any _child_ serializers (eg. relationships, includes and such).

To get your params available in the underlying serializers, just pass them to the main serializer. Consider this:
```ruby
ApplicantIndexSerializer.new(paged_collection, params: {your_stuff_goes: :here}).serializable_hash

```

Let me know if it worked. :bow:

**Comment by nirmal-vaja** [comment]
Hey @stas,

This didn't worked. Have  you got any other idea?

**Comment by nirmal-vaja** [comment]
Hey @gastoncusimano ,

Have you came up with any way to do this?

**Comment by davebream** [comment]
I can also confirm that `params` are not passed down to child serializers

**Comment by rnevius** [comment]
Bumping this, as I've experienced the same issue.

**Comment by gregmalcolm** [comment]
Confirming @stas' solution works for me too. I came to the same conclusion after looking through this:
https://github.com/jsonapi-serializer/jsonapi-serializer/blob/master/lib/fast_jsonapi/object_serializer.rb
