### ISSUE TITLE
Can't use `return` in an `attribute`

### ISSUE THREAD

**Issue by scottrobertson** [jsonapi-serializer/jsonapi-serializer#189]
Tried searching for this, but I cannot find anything. Sorry if it's been discussed already.

Is there a reason why `return` is not allowed in a custom attribute? It makes the code so much messier without being able to use that. For example, I want to write:

```ruby
attribute :blah do |object|
  return 'hello' if object.blah?
  return 'goodbye' if object.something_else?
  
  'default'
end
```

But that results in:

`LocalJumpError (unexpected return):`

Instead, you have to write something like:

```ruby
attribute :blah do |object|
  if object.blah?
    'hello'
  elsif object.something_else?
    'goodbye'
   else
    'default'
  end
end
```

Which is obviously fine there, but as things get more complex, it becomes super messy.

**Comment by stas** [comment]
@scottrobertson I believe this is what you're looking for:
https://stackoverflow.com/questions/2518075/how-can-i-return-something-early-from-a-block

For a bit more context, `attribute` DSL basically creates a block that is being called by the serializer. This is why using a `return` statement causes a syntax error.

I hope this helps. I'll be closing the ticket, but feel free to continue the conversation if you have questions.

**Comment by scottrobertson** [comment]
> @scottrobertson I believe this is what you're looking for:
> https://stackoverflow.com/questions/2518075/how-can-i-return-something-early-from-a-block
> 
> For a bit more context, `attribute` DSL basically creates a block that is being called by the serializer. This is why using a `return` statement causes a syntax error.
> 
> I hope this helps. I'll be closing the ticket, but feel free to continue the conversation if you have questions.

Thank you.

It may be worth documenting this somewhere, as from a users point of view, it feels very odd to have to use `break/next` here, especially when coming from Active Model Serializers.

**Comment by stas** [comment]
@scottrobertson as I already mentioned, this is pure Ruby syntax. It really doesn't have anything to do with AMS vs this gem. I appreciate the feedback, but it's simply out of our scope to document how Ruby works :hugs:

**Comment by mooventhan-k** [comment]
```
attribute :blah do |object|
  return 'hello' if object.blah?
  return 'goodbye' if object.something_else?
  
  'default'
end
```


instead we can use
```
attributes :blah
def blah
  return 'hello' if object.empty?
  .
  .
  'default'
end
```
