### ISSUE TITLE
We're not using ids to identify records. Is it possible to configure jsonapi-serializer to use another identifying attribute?

### ISSUE THREAD

**Issue by holdenhinkle** [jsonapi-serializer/jsonapi-serializer#190]
Hi there!

We're not using ids to identify records. We're using `slug` or another attribute.

Is it possible to set the identifying attribute for a record within each serializer and not include its id? Or is including `id` part the of specification?

Thank you!

**Comment by holdenhinkle** [comment]
I just read [part of the specification ](https://jsonapi.org/format/#document-resource-object-identification)and see that

> Every resource object **MUST** contain an `id` member and a `type` member. The values of the `id` and `type` members **MUST** be strings.

I would love to be able to set the value of `id` to the value of another attribute, like `slug` for example:

```
  "included": [
    {
      "id": "slime",
      "type": "category",
      "attributes": {
        "name": "slime",
        "description": "All the slimes",
        "image": null,
        "slug": "slime"
      }
    }
  ]
```

**Comment by stas** [comment]
@holdenhinkle please take a look at the API of the `set_id` method:
https://github.com/jsonapi-serializer/jsonapi-serializer#customizable-options

I believe that's what you're looking for. Please feel free to leave an update, though I'll be closing this ticket.
