### ISSUE TITLE
Limit recursion

### ISSUE THREAD

**Issue by vitobotta** [jsonapi-serializer/jsonapi-serializer#208]
## Expected Behavior

I would like to be able to somehow limit recursion when in some cases I have serializers that can reference each other.

## Actual Behavior

Due to serializers referencing each other, I have some endpoints that cause hundreds of SQL queries and eventually time out.

## Steps to Reproduce the Problem

  1. Have serializers that reference each other
  2.
  3.

## Specifications

  - Version: 2.2.0
  - Ruby version: 3.0.3

Thanks in advance for any suggestions :)

**Comment by stas** [comment]
Hi there @vitobotta 

Have you considered using paginated responses?



> Due to serializers referencing each other, I have some endpoints that cause hundreds of SQL queries and eventually time out.

This sounds like there's something _funny_ in the way you guys are using the serializers. Try to not create circular dependencies within the same serializer via `include` and such. Not sure I have other ideas, but if you post some examples for the context, I'd be happy to look into it.

**Comment by vitobotta** [comment]
Sorry, I forgot to update this to say I applied some optimizations to solve the problem. Thanks!
