### ISSUE TITLE
Exclude `self` link from serializing

### ISSUE THREAD

**Issue by omar-countable** [jsonapi-serializer/jsonapi-serializer#211]
Hey there!

## Expected Behavior
I'm trying to serialize an object without its self link, so far I've tried:
```ruby
class MyClass < ApplicationSerializer
  link :self, if: -> (_object, _params) { false }
  attributes :myattr1, :myattr2
end
```
and also
```ruby
class MyClass < ApplicationSerializer
  link :self do |_object|
    nil
  end
  attributes :myattr1, :myattr2
end
```

My expectation is something like:

```json
{
  "data": {
    "id": "1",
    "type": "my_class",
    "attributes": {
      "myattr1": "value",
      "myattr2": "value"
    },
    "links": {}
  }
}
```
Or maybe even no `links` field at all, inside or outside the `data` field, but instead...

## Actual Behavior
I'm getting:

```json
{
  "data": {
    "id": "1",
    "type": "my_class",
    "attributes": {
      "myattr1": "value",
      "myattr2": "value"
    },
    "links": {}
  },
  "links": {
    "self": "link-to-self"
  }
}
```
## Steps to Reproduce the Problem

  1. Try to exclude self link from a serializer

## Specifications

  - Version: 2.2.0
  - Ruby version: 2.7.2

Thank you!!!

**Comment by omar-countable** [comment]
My current solution:
```ruby
payload = MyClassSerializer.new(object).serializable_hash.except(:links).to_json
render json: payload
```
🤷

**Comment by stas** [comment]
> Or maybe even no `links` field at all, inside or outside the `data` field, but instead...

Hey, sorry for the late reply.
The JSONAPI spec suggests there should be no _empty_ `links`:
https://jsonapi.org/format/#document-links

At the moment we keep the `links` with a self and I don't think there's a way to remove it. But you can obviously create a `BaseSerializer` that patches `serializable_hash` to return a _link-less_ payload.
