### ISSUE TITLE
Add attribute in options?

### ISSUE THREAD

**Issue by curtis741** [jsonapi-serializer/jsonapi-serializer#212]
I have a one of request where I want to include a count of items a user has. I've got this querry:
```
User.joins(:items).select('users.*, count(items.id) as items_count').group('users.id').order('items_count desc')
```

And wondering about the best way to include "items_count" as an attribute in this case. I'm going to take this approach for now:
```
class TopUsers < Users
  attribute :items_count
end
```
it just seems a bit clunky to make a whole serializer for this one off endpoint. I feel like I should be able to do this?
`UserSerializer.new(users, { add_attribute: [:items_count] })`

Where that option is just injecting an extra attribute into the serializer itself. Thoughts?

**Comment by stas** [comment]
> Where that option is just injecting an extra attribute into the serializer itself. Thoughts?

Huh, nope lol. A bit more context, a serializer attribute should play well with the `fields` and `includes` API. So it's not really interesting to explore this direction because it would simply not be backwards compatible with the rest of the features.
