### ISSUE TITLE
Boilerplate-free way to convert to camelCase?

### ISSUE THREAD

**Issue by chrissyast** [jsonapi-serializer/jsonapi-serializer#215]
I have seen this library linked in many solutions to converting all of the attribute names from snake case to camel case, but from reading the documentation it seems that a serializer is needed for every single model. Is there a way to just change everything to camel case by default?

**Comment by stas** [comment]
@chrissyast apologies for the late reply.

Technically you should be able to use the key transforms option to change the naming scheme.
https://github.com/jsonapi-serializer/jsonapi-serializer#key-transforms
