### ISSUE TITLE
Can we have a new release on Rubygems?

### ISSUE THREAD

**Issue by matheussilvasantos** [jsonapi-serializer/jsonapi-serializer#216]
Most recent changes for making it work with Ruby 3 aren't published there, https://github.com/jsonapi-serializer/jsonapi-serializer/pull/160, for example.

**Comment by stas** [comment]
> Most recent changes for making it work with Ruby 3 aren't published there, #160, for example.

Hey @matheussilvasantos we're using the current version on Ruby v3 without any issues, do you have something specific in mind?

**Comment by matheussilvasantos** [comment]
The last update [here](https://rubygems.org/gems/jsonapi_serializer) is from 2018. Could you release a new version there?

**Comment by krisquigley** [comment]
The latest version is here https://rubygems.org/gems/jsonapi-serializer

> The last update [here](https://rubygems.org/gems/jsonapi_serializer) is from 2018. Could you release a new version there?

The latest version is here https://rubygems.org/gems/jsonapi-serializer

**Comment by matheussilvasantos** [comment]
oh 🤦
