### ISSUE TITLE
meta per Resource Identifier Objects for relationship

### ISSUE THREAD

**Issue by curtis741** [jsonapi-serializer/jsonapi-serializer#221]
As I read the spec here:
https://jsonapi.org/format/#document-resource-identifier-objects

I should be able to put a meta object on each object within a has_many relationship. 

Right now it only supports having a meta on the relationship itself, not on each object within the relationship.

A resource must contain one of the following: `links`, `meta` or `data`. A `data` object is referred to as a `resource linkage`. A `resource linkage`  can be `{}`, `[]`, a single `resource identifier objects` or many `resource identifier objects`. A `resource identifier` **must** include an `id` and `type` but **may** also include a `meta` field.

Given the above summary of the spec, shouldn't I be able to get this?
## Expected Behavior

```
"relationships": {
   "users": {
        "data": [
          { "type": "user", "id": "5", meta: { "some": "key" } },
          { "type": "user", "id": "12", meta: {"other": "data"} }
        ]
      }
}
```

## Actual Behavior
Only possible to do this:
```
"relationships": {
   "users": {
        meta: { "some": "key" },
        "data": [
          { "type": "user", "id": "5",  },
          { "type": "user", "id": "12" }
        ]
      }
}
```

I also think you should be able to combine them. a `meta` on the overall relationship and then a `meta` within each record. Am I reading the spec correctly on this aspect?

## Specifications

  - Version: 2.2
  - Ruby version: 2.7.5

**Comment by stas** [comment]
> A `resource identifier` **must** include an `id` and `type` but **may** also include a `meta` field.

Indeed it's no a requirement. Both payloads you shared are valid.

Please let me know if I can help clarify this in a better way.
