### ISSUE TITLE
Use of cache doesn't seem to speed up much

### ISSUE THREAD

**Issue by vitobotta** [jsonapi-serializer/jsonapi-serializer#227]
## Expected Behavior

Using cache should improve performance significantly.

## Actual Behavior

For example I have an endpoint that serializes 7700 records that also include associations. The queries are fast, but generating the serialized response takes 5 seconds at least (I'm already using the oj gem).

I have enabled caching and I can see it creates one individual Redis key for each record and for its associated records too.
But the serialization takes more or less the same time basically.

## Steps to Reproduce the Problem

  1. Add caching configuration to the relevant models (main model as well as the associated models)
  2. Run the serializer the first time, it creates the keys in Redis
  3. Run the serializer the second time with the same data, this is not faster than without caching

## Specifications

  - Version: 2.2.0
  - Ruby version: 3.1.2

Thanks in advance.

**Comment by stas** [comment]
@vitobotta could you put together some numbers to help compare the expectations vs. the reality.

To me, serializing 7700 records suggests you're doing something wrong, but let's leave this aside and actually review what's going on.

A bit more context on how caching works here. The cache is per record, aka, serializing a collection, still requires fetching every record from the cache. If you want to cache a request fully, that's a different story. As far as I can explain, the caching was designed to avoid hitting the database for repetitive datasets, especially when using includes.

Happy to help figure things out...

**Comment by stas** [comment]
No worries, happy to help. Yeah, it's sort of a different concern re caching here. Ty for reaching out :hugs:
