### ISSUE TITLE
Fields option is cached

### ISSUE THREAD

**Issue by jordant0** [jsonapi-serializer/jsonapi-serializer#90]
Suppose we have the following serializer

```rb
class UserSerializer
  include FastJsonapi::ObjectSerializer
  cache_options store: Rails.cache, namespace: 'fast-jsonapi', expires_in: 12.hours

  attributes :username, :email, :firstname, :lastname
end
```

If we initialize the serializer with `fields` option, the resulting filtered JSON is cached

```rb
UserSerializer.new(user, fields: { user: %i[first_name last_name] }).serializable_hash
# {:data=>
#  {:id=>"1",
#   :type=>:user,
#   :attributes=>{:first_name=>"John", :last_name=>"Doe"},
#   :relationships=>{}}}
```

## Expected Behavior

Subsequent instances of to `UserSerializer` should respect their own `fields` option

```rb
UserSerializer.new(user).serializable_hash
# {:data=>
#  {:id=>"1",
#   :type=>:user,
#   :attributes=>
#    {:username=>"john.doe.1",
#     :first_name=>"John",
#     :last_name=>"Doe"
#     :email=>"johndoe@gmail.com"},
#   :relationships=>{}}}

UserSerializer.new(user, fields: { user: %i[email] }).serializable_hash
# {:data=>
#  {:id=>"1",
#   :type=>:user,
#   :attributes=>{:email=>"johndoe@gmail.com"},
#   :relationships=>{}}}
```

## Actual Behavior

All subsequent calls to the serializer will return with first sparse fieldsets regardless of specified `fields` option until the cache is cleared.

```rb
UserSerializer.new(user).serializable_hash
# {:data=>
#  {:id=>"1",
#   :type=>:user,
#   :attributes=>{:first_name=>"John", :last_name=>"Doe"},
#   :relationships=>{}}}

UserSerializer.new(user, fields: { user: %i[email] }).serializable_hash
# {:data=>
#  {:id=>"1",
#   :type=>:user,
#   :attributes=>{:first_name=>"John", :last_name=>"Doe"},
#   :relationships=>{}}}
```

## Specifications

  - Version: 1.7.2
  - Ruby version: 2.6.5

---

Since `fields` is specify for each instance of the serializer, it should probably be applied after data is stored in the cache so each instance can filter fields independent of each other.

Alternatively, if the record `cache_key` can be dynamically generated based on the serializer instance options, the `fields` can be included as part of  `cache_key`.

**Comment by stas** [comment]
@jordant0 thanks for reporting this...

It looks like the [ActiveSupport::Cache::Store](https://api.rubyonrails.org/classes/ActiveSupport/Cache/Store.html) allows the namespace to be a proc... but it doesn't receive any args. What we could do is to decorate the `namespace` parameter to include the serializer `params` though... Alternatively, you might want to explore using a local variable outside and within the namespace proc you pass, but obviously it's not ideal... Let us know if you find it useful...
