### ISSUE TITLE
[Help] Is there a way to add attributes at run time? (dynamic attributes)

### ISSUE THREAD

**Issue by delphaber** [jsonapi-serializer/jsonapi-serializer#96]
Hi :)

I have a `Model` and I do not know at design time how many attributes it could have, because, for example, they comes from json objects stored in database.

Is there a way for `ModelSerializer` to include these attributes in the `attributes` result key?

Right know I do something like this in the serializer:

```
attribute :foobar do |object|
  object.json_from_db.to_hash # { apples: 4, eggs: 10 }
end
```

and this generates an output like this:

`{ data: [ { id: '2324234',  type: 'model', attributes: { foobar: { apples: 4, eggs: 10 } } } ] }`

but I'd like to have something like this:

 `{ data: [ { id: '2324234',  type: 'model', attributes: { apples: 4, eggs: 10 } } ] }`

Thank you for your time :)

**Comment by stas** [comment]
Heya!

Unfortunately nope and I don't think that's a great idea since it makes things like sparse fields really inconsistent.

Generally speaking you can generate on-the-fly serializer classes and feed the objects to them... but again... that's more of a concern of the end-user.

I hope this answers your question :hugs:

**Comment by delphaber** [comment]
hi @stas thanks for the reply! I understand your concern :) 

I managed it doing something like this, if anyone coming here is interested :)

```ruby
  def self.attributes_hash(record, fieldset = nil, params = {})
    result = super
    result.merge!(result.delete(:foobar))
  end
```

**Comment by delphaber** [comment]
Being able to override the default behaviour with a 10 minutes read of the code and 3 lines of code is a big pro for me! :) Great work
