### ISSUE TITLE
Queries are not optimized when using associations

### ISSUE THREAD

**Issue by csalvato** [jsonapi-serializer/jsonapi-serializer#97]
## Expected Behavior
When using associations in a serializer, such as `belongs_to` or `has_many`, relationships should use `.includes` to eager load data for optimized queries.

## Actual Behavior
`includes` is not being used, causing unoptimized queries.

## Steps to Reproduce the Problem

Create relationships as follows:

```ruby
class User < ApplicationRecord
  has_many :klasses_coaches, foreign_key: 'coach_id', dependent: :destroy, inverse_of: :coach
  has_many :klasses, through: :klasses_coaches
end
```

```ruby
class Klass < ApplicationRecord
  has_many :klasses_coaches, dependent: :destroy
  has_many :coaches, through: :klasses_coaches
end
```

```ruby
class KlassesCoach < ApplicationRecord
  belongs_to :coach, class_name: "User"
  belongs_to :klass
end
```

```ruby
class KlassSerializer
  include JSONAPI::Serializer

  has_many :coaches, serializer: :coach
end
```

```ruby
class CoachSerializer
  include JSONAPI::Serializer
  set_type :coach
  set_key_transform :camel_lower
  has_many :klasses
end
```

```shell
W, [2020-06-28T19:59:00.566479 #58124]  WARN -- : user: redacted
GET /facilities/2/classes?date=2020-07-04T00:00:00-06:00
USE eager loading detected
  Klass => [:klasses_coaches]
  Add to your query: .includes([:klasses_coaches])
Call stack
  /Users/csalvato/leevo/app/controllers/facilities/klasses_controller.rb:26:in `render_classes_for_date'
  /Users/csalvato/leevo/app/controllers/facilities/klasses_controller.rb:6:in `index'


W, [2020-06-28T19:59:00.566528 #58124]  WARN -- : user: redacted
GET /facilities/2/classes?date=2020-07-04T00:00:00-06:00
USE eager loading detected
  Klass => [:coaches]
  Add to your query: .includes([:coaches])
Call stack
  /Users/csalvato/leevo/app/controllers/facilities/klasses_controller.rb:26:in `render_classes_for_date'
  /Users/csalvato/leevo/app/controllers/facilities/klasses_controller.rb:6:in `index'
```

Then run the serializer like so, `KlassSerializer.new(klass, include: [:coaches])`, and the query is not including `klasses_coaches` and `coaches` data.

This was surfaced by using the [Bullet gem](https://github.com/flyerhzm/bullet) in my rails application, and it is producing the following error:

## Specifications

  - Version: 2.0.0
  - Ruby version: 2.6.5

**Comment by stas** [comment]
@csalvato thank you for reporting this, but your request is out of scope of this library.

The goal of this project is to provide a fast and correct JSON:API serialization for **any Ruby object**, be that an ActiveRecord model or just a PORO. To optimize the queries, please consider calling `includes()` before passing a relationship to the serializer.

So instead of
```ruby
KlassSerializer.new(klass, include: [:coaches])
```
you'll end up with something like:
```
KlassSerializer.new(Klass.includes(:coaches), include: [:coaches])
```

I'm closing this fow now, I hope this helped.

**Comment by csalvato** [comment]
@stas Thank you! This was just what I needed to know!  Maybe this should be present somewhere in the README?

If you agree, I can open a PR adding some instructions on how to avoid unoptimized queries when using this gem.  If you think that's on the developer to know, though, I am happy to just leave it as is.

This definitely helped, so thank you so much!

**Comment by stas** [comment]
@csalvato that sounds great! We also have a `docs` folder for all kind of guides. Feel free to put it there and just mention it in the readme :bow: :upside_down_face:
