### ISSUE TITLE
Remove instrumentation for serialized_json ?

### ISSUE THREAD

**Issue by delphaber** [jsonapi-serializer/jsonapi-serializer#98]
I included this line

`require 'fast_jsonapi/instrumentation/serialized_json'`

and got this:

`/xxxxx/jsonapi-serializer-2.0.0/lib/fast_jsonapi/instrumentation/serialized_json.rb:5:in `<module:ObjectSerializer>': undefined method `serialized_json' for module `FastJsonapi::ObjectSerializer' (NameError)`

I think that's because `serialized_json` has been removed (I read that in the changelog).

Shall we remove `fast_jsonapi/instrumentation/serialized_json` from this repo and update the Readme? :)

**Comment by stas** [comment]
@delphaber you're right, looks like something we missed.

The Skylight integration is already broken, more context here #39 
So the plan is to make it a separate gem, or ideally maintain this integration as part of the skylight gem. Do you mind if we move the conversation there?

**Comment by stas** [comment]
Handled in 72f3ae64ddad3092572609da5dcf6f5fba4907e7

Thank you @delphaber
