### ISSUE TITLE
Feature request: meta field on relationships

### ISSUE THREAD

**Issue by mperice** [jsonapi-serializer/jsonapi-serializer#99]
As suggested [here](https://github.com/Netflix/fast_jsonapi/issues/420#issue-446329753) currently this feature is still missing from the serializer.

> Per the spec v1.0  #(emphasis added):
> 
>> A “relationship object” MUST contain at least one of the following:
> >
> > links: ...
> > data: ...
> > meta: a meta object that contains non-standard meta-information about the relationship.
> 
> Right now, serializer relationships support the first two options (https://github.com/Netflix/fast_jsonapi#links-on-a-relationship) but not the last.

I'll try to make a pull request and implement this.

**Comment by stas** [comment]
Closed in #100 

Congrats on the :100: issue/pr :raised_hands:
